name: Acquire Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Request manual activation file
        id: get_manual_license_file
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.3.1f1

      - name: Upload activation file artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: ${{ steps.get_manual_license_file.outputs.filePath }}
          if-no-files-found: error
